import i18nConfig from '@/i18nConfig';
import '../../globals.scss';
import '../../bootstrap-grid.min.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Providers } from '../../redux/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  return (
    <Providers>
      <html lang={locale}>
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
